# Generated by Django 6.1.1 on 2026-10-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('resumo', models.TextField(max_length=500)),
                ('conteudo', models.TextField()),
                ('destaque_home', models.BooleanField(default=False, verbose_name='Exibir em Notícias e Eventos')),
                ('conquista_destaque', models.BooleanField(default=False, verbose_name='Exibir em Conquistas que falam por Si')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
